data_dir: ./data/openwebtext

block_size: 1024
  
optimizer_config:
  learning_rate: 6e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95

trainer_config:
  backend: gloo
  device: cpu
  mixed_precision: bf16 # fp32 or bf16.
  compile: False
  eval_interval: 5
  log_interval: 1
  eval_iters: 2
  eval_only: False
  wandb_log: False
  batch_size: 32
  max_iters: 10
  model_path: ckpt.pt
  snapshot_path: snapshot.pt
  gradient_accumulation_steps: 2 # 1x8 (num_nodes x step)
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 2
  lr_decay_iters: 20
  max_lr: 6e-4
  min_lr: 6e-5